### ISSUE TITLE
Imported TODO list

### ISSUE THREAD

**Issue by AfroThundr3007730** [AfroThundr3007730/syncrepo#1]
From the [original gist](https://gist.github.com/AfroThundr3007730/d813dc149b2407cf53936915e98659af):

RepoSync TODO / Roadmap
=======================

* [ ] Documentation
  * [ ] Changelog (prob. from git history)
  * [x] Version Header
  * [x] Help / Usage (WIP)
  * [x] Also Cmd Options (WIP)
  * [ ] Populate the wiki
* [ ] Refactoring
  * [x] Export Functions
  * [x] Combine Apt / Yum
  * [x] Combine US / DS
  * [ ] Fix Assumptions (WIP)
  * [ ] State / sanity checking
* [ ] Config File
  * [ ] Distros / Versions select
  * [x] Sync Behavior flags
  * [ ] Mirror Types
  * [ ] Auto-Generate Option
* [ ] Installation
  * [ ] Auto Repo Init
  * [ ] Dependency Install
  * [ ] Service Creation
  * [ ] Rsync / HTTP Config
  * [ ] Sync System User
* [ ] Testing

Misc. Notes & TODO (eventually)
-----------

* Move to separate repo - done
* Single-file distribution
* Build system, auto signing
* Detailed docs (built in) 
* Cross-distro portability (even BSD)
